CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(180),
	`searchRunId` int,
	`categoria` varchar(160),
	`nome` varchar(220) NOT NULL,
	`telefone` varchar(40) NOT NULL,
	`whatsapp_valido` boolean,
	`whatsapp_jid` varchar(100),
	`estrelas` decimal(3,1) DEFAULT '0',
	`avaliacoes` int DEFAULT 0,
	`endereco` text,
	`cidade` varchar(120),
	`estado` varchar(80),
	`regiao` varchar(120),
	`status` varchar(60) NOT NULL DEFAULT 'Novo',
	`campanhas` varchar(180),
	`tem_site` varchar(10),
	`site` text,
	`instagram` text,
	`facebook` text,
	`qualificationStatus` enum('pending','qualified','discarded') NOT NULL DEFAULT 'pending',
	`qualificationScore` int,
	`qualificationReason` text,
	`readyToSend` boolean NOT NULL DEFAULT false,
	`rawData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_telefone_unique` UNIQUE(`telefone`)
);
--> statement-breakpoint
CREATE TABLE `search_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`niche` varchar(160) NOT NULL,
	`city` varchar(120),
	`state` varchar(80),
	`region` varchar(120),
	`status` enum('draft','queued','running','completed','failed') NOT NULL DEFAULT 'queued',
	`source` varchar(40) DEFAULT 'apify',
	`n8nExecutionId` varchar(120),
	`leadsCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `search_runs_id` PRIMARY KEY(`id`)
);
